/**
 * Build script to generate careers manifest for Cloudflare Workers compatibility.
 *
 * This script:
 * 1. Reads all MDX files from content/careers
 * 2. Compiles them to plain React components (no MDX runtime needed)
 * 3. Generates metadata manifest and component files
 *
 * Run with: bun scripts/generate-careers.ts
 */

import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { compile } from "@mdx-js/mdx";

const CONTENT_DIR = path.join(process.cwd(), "src/content/careers");
const OUTPUT_DIR = path.join(process.cwd(), "src/lib/generated");
const METADATA_FILE = path.join(OUTPUT_DIR, "careers.ts");
const COMPONENTS_DIR = path.join(OUTPUT_DIR, "careers");

interface CareerFrontmatter {
  title: string;
  department: string;
  location: string;
  type: "full-time" | "part-time" | "contract" | "internship";
  excerpt: string;
  postedDate: string;
}

interface CareerMetadata {
  slug: string;
  title: string;
  department: string;
  location: string;
  type: "full-time" | "part-time" | "contract" | "internship";
  excerpt: string;
  postedDate: string;
}

/**
 * Convert slug to PascalCase for component name
 */
function toPascalCase(slug: string): string {
  return slug
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

async function generateCareers(): Promise<void> {
  console.log("Generating careers manifest...");

  // Ensure output directories exist
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }
  if (!fs.existsSync(COMPONENTS_DIR)) {
    fs.mkdirSync(COMPONENTS_DIR, { recursive: true });
  }

  // Check if content directory exists
  if (!fs.existsSync(CONTENT_DIR)) {
    console.warn(`Content directory not found: ${CONTENT_DIR}`);
    await writeEmptyManifests();
    return;
  }

  // Read all MDX files
  const fileNames = fs.readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".mdx"));

  if (fileNames.length === 0) {
    console.warn("No MDX files found in careers content directory");
    await writeEmptyManifests();
    return;
  }

  const careers: CareerMetadata[] = [];

  // Compile each MDX file
  for (const fileName of fileNames) {
    const slug = fileName.replace(/\.mdx$/, "");
    const fullPath = path.join(CONTENT_DIR, fileName);
    const fileContents = fs.readFileSync(fullPath, "utf8");
    const matterResult = matter(fileContents);

    const frontmatter = matterResult.data as CareerFrontmatter;

    careers.push({
      slug,
      title: frontmatter.title,
      department: frontmatter.department,
      location: frontmatter.location,
      type: frontmatter.type,
      excerpt: frontmatter.excerpt,
      postedDate: frontmatter.postedDate,
    });

    // Compile MDX to JavaScript module
    const compiled = await compile(matterResult.content, {
      outputFormat: "program",
      jsx: false,
      jsxImportSource: "react",
      development: false,
      providerImportSource: undefined,
    });

    // Add "use client" directive
    const componentCode = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Compiled from src/content/careers/${fileName}
 */

"use client";

${String(compiled)}`;

    const componentPath = path.join(COMPONENTS_DIR, `${slug}.jsx`);
    fs.writeFileSync(componentPath, componentCode, "utf8");
    console.log(`  Compiled: ${slug}.jsx`);
  }

  // Sort by posted date (newest first)
  careers.sort((a, b) => (a.postedDate < b.postedDate ? 1 : -1));

  // Generate metadata file
  const metadataOutput = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-careers.ts
 *
 * Career position metadata for listing pages.
 */

export interface CareerMetadata {
  slug: string;
  title: string;
  department: string;
  location: string;
  type: "full-time" | "part-time" | "contract" | "internship";
  excerpt: string;
  postedDate: string;
}

export const careers: CareerMetadata[] = ${JSON.stringify(careers, null, 2)};
`;

  fs.writeFileSync(METADATA_FILE, metadataOutput, "utf8");
  console.log(`Generated metadata for ${careers.length} careers to ${METADATA_FILE}`);

  // Generate index file for components
  const slugs = careers.map((c) => c.slug);
  const imports = slugs
    .map((slug) => `import ${toPascalCase(slug)}Career from "./careers/${slug}.jsx";`)
    .join("\n");

  const registryEntries = slugs
    .map((slug) => `  "${slug}": ${toPascalCase(slug)}Career,`)
    .join("\n");

  const indexOutput = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-careers.ts
 *
 * Registry of pre-compiled career position components.
 */

import type { ComponentType } from "react";

${imports}

const careerComponents: Record<string, ComponentType> = {
${registryEntries}
};

export function getCareerComponent(slug: string): ComponentType | null {
  return careerComponents[slug] ?? null;
}

export function careerExists(slug: string): boolean {
  return slug in careerComponents;
}

export const availableSlugs = ${JSON.stringify(slugs)} as const;
export type CareerSlug = (typeof availableSlugs)[number];
`;

  fs.writeFileSync(path.join(OUTPUT_DIR, "career-components.tsx"), indexOutput, "utf8");
  console.log("Generated career component registry");
}

async function writeEmptyManifests(): Promise<void> {
  const metadataOutput = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-careers.ts
 */

export interface CareerMetadata {
  slug: string;
  title: string;
  department: string;
  location: string;
  type: "full-time" | "part-time" | "contract" | "internship";
  excerpt: string;
  postedDate: string;
}

export const careers: CareerMetadata[] = [];
`;

  const indexOutput = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-careers.ts
 */

import type { ComponentType } from "react";

const careerComponents: Record<string, ComponentType> = {};

export function getCareerComponent(slug: string): ComponentType | null {
  return careerComponents[slug] ?? null;
}

export function careerExists(slug: string): boolean {
  return slug in careerComponents;
}

export const availableSlugs = [] as const;
export type CareerSlug = never;
`;

  fs.writeFileSync(METADATA_FILE, metadataOutput, "utf8");
  fs.writeFileSync(path.join(OUTPUT_DIR, "career-components.tsx"), indexOutput, "utf8");
  console.log("Generated empty career manifests");
}

generateCareers().catch(console.error);
