/**
 * Build script to generate posts manifest for Cloudflare Workers compatibility.
 *
 * Cloudflare Workers don't have filesystem access at runtime, so we need to
 * bundle all blog content at build time. This script reads all MDX files and
 * generates a TypeScript file with the content embedded.
 *
 * Run with: bun scripts/generate-posts.ts
 */

import fs from "fs";
import path from "path";
import matter from "gray-matter";

const CONTENT_DIR = path.join(process.cwd(), "src/content/blog");
const OUTPUT_FILE = path.join(process.cwd(), "src/lib/generated/posts.ts");

interface PostFrontmatter {
  title: string;
  date: string;
  excerpt: string;
  author: string;
}

interface GeneratedPost {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  authorId: string;
  content: string;
}

function generatePosts(): void {
  console.log("Generating posts manifest...");

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Check if content directory exists
  if (!fs.existsSync(CONTENT_DIR)) {
    console.warn(`Content directory not found: ${CONTENT_DIR}`);
    writeEmptyManifest();
    return;
  }

  // Read all MDX files
  const fileNames = fs.readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".mdx"));

  if (fileNames.length === 0) {
    console.warn("No MDX files found in content directory");
    writeEmptyManifest();
    return;
  }

  const posts: GeneratedPost[] = fileNames.map((fileName) => {
    const slug = fileName.replace(/\.mdx$/, "");
    const fullPath = path.join(CONTENT_DIR, fileName);
    const fileContents = fs.readFileSync(fullPath, "utf8");
    const matterResult = matter(fileContents);

    const frontmatter = matterResult.data as PostFrontmatter;

    return {
      slug,
      title: frontmatter.title,
      date: frontmatter.date,
      excerpt: frontmatter.excerpt,
      authorId: frontmatter.author,
      content: matterResult.content,
    };
  });

  // Sort by date (newest first)
  posts.sort((a, b) => (a.date < b.date ? 1 : -1));

  // Generate TypeScript file
  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-posts.ts
 *
 * This file contains all blog post data bundled at build time for
 * Cloudflare Workers compatibility.
 */

export interface GeneratedPost {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  authorId: string;
  content: string;
}

export const posts: GeneratedPost[] = ${JSON.stringify(posts, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf8");
  console.log(`Generated ${posts.length} posts to ${OUTPUT_FILE}`);
}

function writeEmptyManifest(): void {
  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-posts.ts
 */

export interface GeneratedPost {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  authorId: string;
  content: string;
}

export const posts: GeneratedPost[] = [];
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf8");
  console.log("Generated empty posts manifest");
}

generatePosts();
